version: '3.8'
services:
  vueapp:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"  # Assuming the dev server runs on 3000
    volumes:
      - .:/app/my-vue-app
      - /app/my-vue-app/node_modules
    environment:
      - NODE_ENV=development
